### ISSUE TITLE
How to use/configure absolute path 

### ISSUE THREAD

**Issue by bart-kochanowicz** [justcoded/web-starter-kit#133]
Production folder structure is different than dev so when I use relative path in dev in my scss file for example: "background: url('../../images/card.png');" it won't work in production because of folder structure. How to fix that? / How to use absolute path?

production:
|      +--/css
|           +-styles.min.css
|      +--/images
|           +-card.png
| index.html

development:
|      +--/scss
|           +--/components <----- one additional folder
|                 +-main.scss  
|      +--/images
|           +-card.png
| index.html

**Comment by sgurin** [comment]
Hi @bartekmajster,

We do not recommend to use absolute path for any kind of sources in the template. 

So, you can use relate path https://prnt.sc/r960t9 https://prnt.sc/r9617r and it will work in production mode without any problems https://prnt.sc/r962du

Your relative path has an issue. It should be with ../  and the folder structure should as our default https://prnt.sc/r9633j Otherwise would require to re-write folder architecture of the build.

**Comment by bart-kochanowicz** [comment]
So, if you do not recommend to use absolute path I just rebuild production folder and everything should work fine.
cool, thank you for support ;)
